# Generated by Django 6.1 on 2026-08-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تمرین')),
                ('description', models.TextField(verbose_name='صورت مسئله')),
                ('starter_code', models.TextField(blank=True, null=True, verbose_name='کد اولیه (استارتر)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(verbose_name='کد ارسالی کاربر')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('passed', 'تایید شده'), ('failed', 'رد شده')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد یا خطای سیستم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='practices.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
