# Generated by Django 6.1 on 2026-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='language',
            field=models.CharField(default='Python', max_length=50, verbose_name='زبان برنامه\u200cنویسی'),
        ),
    ]
