# Generated by Django 6.1 on 2026-09-10 08:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='توضیح پاسخ (بعد از آزمون)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب سوال')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوالات آزمون',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ URL')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='تصویر دوره')),
                ('instructor_name', models.CharField(blank=True, max_length=150, verbose_name='نام نمایشی مدرس')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت نقدی (تومان)')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان؟')),
                ('requires_vip', models.BooleanField(default=True, verbose_name='دسترسی با اشتراک ویژه؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors_courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سرفصل / فصل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='شماره ترتیب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='متن و توضیحات تکمیلی')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ویدیو (استریم/دانلودی)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (دقیقه)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش در فصل')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان؟ (مشاهده بدون خرید)')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع سوال')),
                ('content', models.TextField(verbose_name='متن پرسش')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='حل شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرسش دانشجو',
                'verbose_name_plural': 'پرسش\u200cهای دانشجویان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن پاسخ')),
                ('is_instructor_answer', models.BooleanField(default=False, verbose_name='پاسخ استاد؟')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='پاسخ برگزیده / تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.lessonquestion', verbose_name='پرسش مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ پرسش',
                'verbose_name_plural': 'پاسخ\u200cهای پرسش\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح است؟')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cهای سوال',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات یا راهنمای آزمون')),
                ('pass_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='حداقل نمره قبولی (درصد)')),
                ('time_limit_minutes', models.PositiveIntegerField(default=15, verbose_name='مدت زمان آزمون (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.chapter', verbose_name='مربوط به فصل (اختیاری)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آزمون آنلاین',
                'verbose_name_plural': 'آزمون\u200cهای آنلاین',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='آزمون'),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='نمره کسب شده (درصد)')),
                ('passed', models.BooleanField(default=False, verbose_name='قبول شده؟')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='نوبت تلاش')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اتمام')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.quiz', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نتیجه آزمون',
                'verbose_name_plural': 'نتایج آزمون\u200cها',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='شماره سریال مدرک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/issued/', verbose_name='تصویر نهایی مدرک')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداختی (تومان)')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دوره\u200cها',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lesson', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'یادداشت درس',
                'verbose_name_plural': 'یادداشت\u200cهای دروس',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=True, verbose_name='تکمیل شده؟')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تکمیل')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='courses.lesson', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر',
                'verbose_name_plural': 'پیشرفت\u200cهای کاربران',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
