# Generated by Django 6.1 on 2026-09-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['id']},
        ),
    ]
