# Generated by Django 6.1 on 2026-09-06 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='authority',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='کد اتوریتی زرین\u200cپال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan', verbose_name='پلن خریداری شده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
