# Generated by Django 6.1 on 2026-09-10 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('technical', 'پشتیبانی فنی'), ('financial', 'امور مالی و خرید'), ('educational', 'سوالات آموزشی'), ('other', 'سایر موارد')], max_length=20, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/', verbose_name='فایل ضمیمه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پاسخ'), ('open', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
